# Parameters for YOLOv2 training on VOC2007 dataset.

# The batch size on training.
batch_size: 10
# The height of resized image for train.
train_resized_height: 320
# The width of resized image for train.
train_resized_width: 576
# The height of resized image for validation.
val_resized_height: 320
# The width of resized image for validation.
val_resized_width: 576
# The crop height size for random cropping in training.
train_crop_height: 320
# The crop width size for random cropping in training.
train_crop_width: 576
# The directory path to save logs and models.
save_dir: "./tmp"
# The number of epochs to train.
num_epochs: 1500
# The number of classes to use.
num_classes: 21
# The scales of anchor boxes.
anchor_scale:
  - 8.0
  - 16.0
  - 32.0
# The aspect ratio of anchor boxes.
anchor_aspect_ratio:
  - 0.5
  - 1.0
  - 2.0
# The number of workers for tf.data.Dataset.map().
num_parallel_calls: 10
# The parameter for tf.data.Dataset.prefetch().
prefetch_buffer_size: 10
# If true, random flip image horizontally.
random_flip_left_right: true
# Scale factor used to adjust brightness.
random_brightness: 0.2
# Scale factor used to adjust contrast.
random_contrast: 0.2
# Scale factor used to adjust hue.
random_hue: 0.2
# Scale factor used to adjust saturation.
random_saturation: 0.2
# Parameters for tf.train.polynomial_decay.
learning_rate: 0.002
end_learning_rate: 0.0002
power: 0.9
# The number of training samples. Use to compute decay steps
# for polynomial learning rate.
num_train_samples: 10582
# Evaluate model by validation dataset and save the session
# every @p evaluate_epochs epochs.
evaluate_epochs: 1
# Show metric every @p verbose_step step.
verbose_steps: 10
# The path of .ckpt file to resume session.
# If you use vgg_16, download weights from here:
# http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz
resume_path:
# If specified, resume only model weights from the specified architecture.
# If you use vgg_16 weights, set 'vgg_16'.
finetune_from:
# The parameter for tf.data.Dataset.shuffle().
shuffle_buffer_size: 100
# Path to the cityscapes tfrecord data directory.
# The data should be created by src.data.tfrecord.write_tfrecord.
tfdata_dir: "/home/ubuntu/workspace/local_data/voc/VOCdevkit/VOC2007/tfrecord"
